
import type { Metadata } from "next";
import { poppins, montserrat } from "./fonts";
import "./globals.css";
import Header from "@/components/shared/Header";
import Footer from "@/components/shared/Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${poppins.variable} ${montserrat.variable} hide-scrollbar scroll-smooth xl:w-[1440px] xl:flex xl:flex-col xl:justify-center`}>
      <body
  className={`antialiased` }
      >
       <Header/>
        {children}
        {/* <Footer/> */}
      </body>
    </html>
  );
}
